name: smooth_sheets
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.23.0
