name: Dry Publish
on:
  push:
    branches: [main]

jobs:
  dry-publish:
    name: Dry Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: package
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x

      - run: flutter --version
      - run: flutter pub get

      - uses: axel-op/dart-package-analyzer@master
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: fujidaiti/dart-package-inspector@v1
        with:
          report: ${{ steps.analysis.outputs.json_output }}
          min-convention-points: 30
          min-platform-points: 20
          min-analysis-points: 50
          min-dependency-points: 20
          supported-platforms: ios, android

      - run: flutter pub publish --dry-run
