name: Validation
on:
  pull_request:
  push:
    branches: [main]

env:
  package_dir: ./package

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.package_dir }}

      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: ${{ env.package_dir }}

      - uses: fujidaiti/dart-package-inspector@v1
        with:
          report: ${{ steps.analysis.outputs.json_output }}
          min-pub-points: 130
          supported-platforms: ios, android

      - name: Dry publish
        run: flutter pub publish --dry-run
